name: Pull requests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
         
      - name: Build all configurations
        run: ./gradlew assembleDebug

      - name: Upload APK as Artifacts
        uses: actions/upload-artifact@v2.2.0
        with:
          name: locer-android
          path: |
            **/*.apk
